# -*- coding: utf-8 -*-
"""tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbaU3A6Vf82DBVkXQ1cbt947ja70WxMb
"""

!pip install gtts

"""
Text-to-Speech Module - Clean Version
Conversion texte vers audio pour réponses médicales
"""

import os
import hashlib
from pathlib import Path
from typing import Optional, Dict, List

# Vérification dépendances
try:
    from gtts import gTTS
    GTTS_AVAILABLE = True
except ImportError:
    GTTS_AVAILABLE = False

try:
    from TTS.api import TTS as CoquiTTS
    COQUI_AVAILABLE = True
except ImportError:
    COQUI_AVAILABLE = False


class TextToSpeech:
    """
    Convertit du texte en audio
    Backends: gTTS (rapide, en ligne) ou Coqui TTS (offline, qualité)
    """

    def __init__(
        self,
        backend: str = "gtts",
        language: str = "en",
        speed: float = 1.0,
        output_dir: str = "./audio_output"
    ):
        self.backend = backend
        self.language = language
        self.speed = speed
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True, parents=True)
        self.engine = None

        self._init_engine()

    def _init_engine(self):
        """Initialise le moteur TTS"""
        if self.backend == "gtts":
            if not GTTS_AVAILABLE:
                raise ImportError("gTTS non installé: pip install gtts")
            self.engine = "gtts"
            print(" gTTS prêt")

        elif self.backend == "coqui":
            if not COQUI_AVAILABLE:
                raise ImportError("Coqui TTS non installé: pip install TTS")
            try:
                print(" Chargement Coqui TTS...")
                self.engine = CoquiTTS(
                    model_name="tts_models/en/ljspeech/tacotron2-DDC",
                    progress_bar=False
                )
                print(" Coqui TTS prêt")
            except Exception as e:
                print(f" Erreur Coqui: {e}")
                print(" Basculement vers gTTS")
                self.backend = "gtts"
                self.engine = "gtts"
        else:
            raise ValueError(f"Backend inconnu: {self.backend}")

    def synthesize(
        self,
        text: str,
        output_file: Optional[str] = None
    ) -> Dict:
        """
        Convertit texte en audio

        Args:
            text: Texte à convertir
            output_file: Chemin fichier (auto-généré si None)

        Returns:
            Dict: {success: bool, output_file: str, error: str}
        """
        if not text or not text.strip():
            return {"success": False, "output_file": None, "error": "Texte vide"}

        # Générer nom fichier
        if output_file is None:
            text_hash = hashlib.md5(text.encode()).hexdigest()[:8]
            output_file = self.output_dir / f"audio_{text_hash}.mp3"
        else:
            output_file = Path(output_file)

        try:
            # Prétraitement
            processed_text = self._preprocess_text(text)

            # Synthèse
            if self.backend == "gtts":
                self._synthesize_gtts(processed_text, output_file)
            else:
                self._synthesize_coqui(processed_text, output_file)

            return {
                "success": True,
                "output_file": str(output_file),
                "error": None
            }

        except Exception as e:
            return {
                "success": False,
                "output_file": None,
                "error": str(e)
            }

    def _synthesize_gtts(self, text: str, output_file: Path):
        """Génération avec gTTS"""
        tts = gTTS(
            text=text,
            lang=self.language,
            slow=(self.speed < 0.8)
        )
        tts.save(str(output_file))

    def _synthesize_coqui(self, text: str, output_file: Path):
        """Génération avec Coqui"""
        self.engine.tts_to_file(text=text, file_path=str(output_file))

    def _preprocess_text(self, text: str) -> str:
        """
        Prétraite le texte pour meilleure prononciation
        """
        # Termes médicaux
        replacements = {
            # Hormones
            "AMH": "A M H",
            "FSH": "F S H",
            "LH": "L H",
            "TSH": "T S H",

            # Conditions
            "PCOS": "P C O S",
            "IVF": "I V F",
            "IUI": "I U I",
            "AFC": "A F C",

            # Unités
            "ng/mL": "nanograms per milliliter",
            "mIU/mL": "milli international units per milliliter",
            "pg/mL": "picograms per milliliter"
        }

        # Remplacements
        for term, pronunciation in replacements.items():
            text = text.replace(term, pronunciation)
            text = text.replace(term.lower(), pronunciation.lower())

        # Pauses naturelles
        text = text.replace(". ", "... ")
        text = text.replace("? ", "?.. ")
        text = text.replace("! ", "!.. ")

        return text

    def batch_synthesize(
        self,
        texts: List[str],
        prefix: str = "batch"
    ) -> List[Dict]:
        """
        Convertit plusieurs textes

        Args:
            texts: Liste de textes
            prefix: Préfixe des fichiers

        Returns:
            Liste des résultats
        """
        results = []
        for i, text in enumerate(texts):
            output_file = self.output_dir / f"{prefix}_{i:03d}.mp3"
            result = self.synthesize(text, output_file)
            results.append(result)
        return results


# ============================================
# DEMO
# ============================================

def demo():
    print("="*60)
    print("DEMO: Text-to-Speech")
    print("="*60)

    # Créer TTS
    tts = TextToSpeech(
        backend="gtts",
        language="en",
        speed=1.0,
        output_dir="./demo_audio"
    )

    # Test simple
    test_text = """
    Your AMH level of 1.1 ng/mL is slightly below average,
    but many women with similar levels conceive naturally.
    I recommend consulting a fertility specialist.
    """

    print("\n Synthèse audio...")
    result = tts.synthesize(test_text, output_file="demo_response.mp3")

    if result["success"]:
        print(f" Audio créé: {result['output_file']}")
    else:
        print(f" Erreur: {result['error']}")

    # Test batch
    print("\n Synthèse batch...")
    chunks = [
        "AMH stands for Anti-Müllerian Hormone.",
        "FSH is Follicle Stimulating Hormone.",
        "These hormones assess ovarian reserve."
    ]

    batch_results = tts.batch_synthesize(chunks, prefix="demo_chunk")
    success = sum(1 for r in batch_results if r["success"])
    print(f" {success}/{len(chunks)} conversions réussies")

    print("\n" + "="*60)


if __name__ == "__main__":
    demo()